#!/usr/bin/env python3
"""Convert the legacy MariaDB dump (db/gong.sql) into the Gong-NG SQLite seed.

Build-time tool only — never ships on the appliance. Output is checked in as
ng/seed/seed.sql (and doha-manifest.json); tests/test_seed.py fails the build
if the checked-in seed drifts from this converter's output.

Transforms (see docs/GONG-NG-DESIGN.md §7):
  course_types  -> 1:1, ids preserved
  schedule      -> type=-1 -> course_type_id NULL (no-course set, day NULL)
                   day_no=2 -> day_no NULL (default mid-course pattern)
                   start_time int HHMM -> 'HH:MM'
  courses, settings -> not seeded

Usage: convert_legacy_seed.py [--dump db/gong.sql] [--doha-dir app/dhamma/doha]
                              [--out ng/seed] [--merge extra_dump.sql]
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


def parse_inserts(sql_text: str, table: str) -> list[tuple]:
    """Return all value-tuples from INSERT INTO `table` VALUES (...),(...);"""
    rows: list[tuple] = []
    pat = re.compile(rf"INSERT INTO `{table}` VALUES (.+?);", re.S)
    for m in pat.finditer(sql_text):
        # SQL tuples of ints and single-quoted strings are valid Python
        # literals once doubled quotes are unescaped.
        literal = "[" + m.group(1).replace("''", "\\'") + "]"
        rows.extend(ast.literal_eval(literal))
    return rows


def hhmm_to_time(t: int) -> str:
    hour, minute = t // 100, t % 100
    if not (0 <= hour <= 23 and 0 <= minute <= 59):
        raise ValueError(f"impossible legacy start_time {t}")
    return f"{hour:02d}:{minute:02d}"


def convert(dump_paths: list[Path]) -> tuple[list[tuple], list[tuple]]:
    course_types: dict[int, tuple] = {}
    events: dict[tuple, tuple] = {}
    for path in dump_paths:
        text = path.read_text(encoding="utf-8", errors="replace")
        for ct_id, name, days, anapana in parse_inserts(text, "course_types"):
            course_types[int(ct_id)] = (int(ct_id), str(name), int(days), int(anapana))
        for _id, typ, day_no, start_time, repeats in parse_inserts(text, "schedule"):
            ct = None if int(typ) == -1 else int(typ)
            day = int(day_no)
            new_day = None if (day == 2 or day == -1) else day
            key = (ct, new_day, hhmm_to_time(int(start_time)))
            row = (*key, int(repeats))
            if key in events and events[key] != row:
                print(f"warning: duplicate event {key}, keeping repeats="
                      f"{events[key][3]}, dropping {repeats}", file=sys.stderr)
                continue
            events[key] = row
    return sorted(course_types.values()), sorted(
        events.values(), key=lambda r: (r[0] is None, r[0] or 0, r[1] is None, r[1] or 0, r[2])
    )


def sql_lit(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def render_seed(course_types: list[tuple], events: list[tuple]) -> str:
    out = [
        "-- Generated by ng/tools/convert_legacy_seed.py from db/gong.sql.",
        "-- Do not edit by hand; re-run the converter.",
        "BEGIN;",
    ]
    for row in course_types:
        out.append(
            "INSERT INTO course_types (id, name, total_days, anapana_days) "
            f"VALUES ({', '.join(sql_lit(v) for v in row)});"
        )
    for row in events:
        out.append(
            "INSERT INTO schedule_events (course_type_id, day_no, time_local, repeats) "
            f"VALUES ({', '.join(sql_lit(v) for v in row)});"
        )
    out.append("COMMIT;")
    return "\n".join(out) + "\n"


def render_manifest(doha_dir: Path) -> str:
    files = sorted(p.name for p in doha_dir.glob("D[0-9][0-9]_*.mp3"))
    if len(files) != 11:
        raise SystemExit(f"expected 11 doha files in {doha_dir}, found {len(files)}")
    return json.dumps({str(i + 1): name for i, name in enumerate(files)}, indent=2) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dump", type=Path, default=REPO / "db" / "gong.sql")
    ap.add_argument("--merge", type=Path, action="append", default=[],
                    help="additional legacy dump(s) from customised units")
    ap.add_argument("--doha-dir", type=Path, default=REPO / "app" / "dhamma" / "doha")
    ap.add_argument("--out", type=Path, default=REPO / "ng" / "seed")
    args = ap.parse_args()

    course_types, events = convert([args.dump, *args.merge])
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "seed.sql").write_text(render_seed(course_types, events))
    (args.out / "doha-manifest.json").write_text(render_manifest(args.doha_dir))
    print(f"{len(course_types)} course types, {len(events)} schedule events "
          f"-> {args.out}/seed.sql")


if __name__ == "__main__":
    main()
