#!/usr/bin/env python3
"""Convert the Deshna appliance MySQL dump into the Gong-NG deshna seed.

Build-time tool only. Source: the deshna Pi's `deshna.sql` (tables: courses,
schedule; languages/course_language are client-side concerns and not needed
by the fetch.php responder). Output: ng/seed/deshna-seed.sql.

Schedule ids MUST be preserved verbatim — the Deshna Android app resolves
track ids against its own bundled DB and sends them to /fetch.php.

Usage: convert_deshna_seed.py --dump /path/to/deshna.sql [--out ng/seed]
"""
from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


def parse_inserts(sql_text: str, table: str) -> list[tuple]:
    rows: list[tuple] = []
    pat = re.compile(rf"INSERT INTO `{table}` VALUES (.+?);\n", re.S)
    for m in pat.finditer(sql_text):
        literal = m.group(1)
        literal = re.sub(r"(?<=[,(])NULL(?=[,)])", "None", literal)
        rows.extend(ast.literal_eval("[" + literal + "]"))
    return rows


def sql_lit(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(int(v))
    return "'" + str(v).replace("'", "''") + "'"


def convert(dump: Path, apk_db: Path | None = None) -> tuple[list[tuple], list[tuple]]:
    """Union of the Pi server dump and (optionally) the Android app's bundled
    SQLite DB. The app DB is a newer revision — its rows win on conflicting
    ids, and its extra ids are appended so current clients resolve; dump-only
    ids are kept so older clients still resolve."""
    text = dump.read_text(encoding="utf-8", errors="replace")
    # courses dump order: (days, id, name, password, folder, priority, enabled)
    courses = {
        int(cid): (int(cid), name, folder, int(days or 0), int(prio or 0),
                   int(enabled))
        for days, cid, name, _password, folder, prio, enabled
        in parse_inserts(text, "courses")
    }
    # schedule dump order matches our table exactly
    schedule = {
        int(sid): (int(sid), track, int(course_id or 0), int(day_no or 0),
                   filename, int(start_time or 0), int(multiple), lang or "",
                   int(valid_till), int(auto_play))
        for sid, track, course_id, day_no, filename, start_time, multiple,
            lang, valid_till, auto_play in parse_inserts(text, "schedule")
    }
    if apk_db is not None:
        import sqlite3
        conn = sqlite3.connect(f"file:{apk_db}?mode=ro", uri=True)
        for days, cid, name, _pw, folder, prio, enabled in conn.execute(
                "SELECT days, id, name, password, folder, priority, enabled"
                " FROM courses"):
            courses[int(cid)] = (int(cid), name, folder, int(days or 0),
                                 int(prio or 0), int(enabled))
        for row in conn.execute(
                "SELECT id, track, course_id, day_no, filename, start_time,"
                " multiple, lang, valid_till, auto_play FROM schedule"):
            sid, track, course_id, day_no, filename, start_time, multiple, \
                lang, valid_till, auto_play = row
            schedule[int(sid)] = (
                int(sid), track, int(course_id or 0), int(day_no or 0),
                filename, int(start_time or 0), int(multiple or 0),
                lang or "", int(valid_till or 0), int(auto_play or 0))
        conn.close()
    return sorted(courses.values()), sorted(schedule.values())


def render(courses: list[tuple], schedule: list[tuple]) -> str:
    out = [
        "-- Generated by ng/tools/convert_deshna_seed.py from the Deshna",
        "-- appliance dump. Do not edit by hand; schedule ids are the",
        "-- contract with the Deshna Android app.",
        "BEGIN;",
    ]
    for row in courses:
        out.append(
            "INSERT INTO deshna_courses (id, name, folder, days, priority,"
            f" enabled) VALUES ({', '.join(sql_lit(v) for v in row)});"
        )
    for row in schedule:
        out.append(
            "INSERT INTO deshna_schedule (id, track, course_id, day_no,"
            " filename, start_time, multiple, lang, valid_till, auto_play)"
            f" VALUES ({', '.join(sql_lit(v) for v in row)});"
        )
    out.append("COMMIT;")
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dump", type=Path, required=True)
    ap.add_argument("--apk-db", type=Path,
                    help="assets/deshna.db from the current app APK")
    ap.add_argument("--out", type=Path, default=REPO / "ng" / "seed")
    args = ap.parse_args()
    courses, schedule = convert(args.dump, args.apk_db)
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "deshna-seed.sql").write_text(render(courses, schedule))
    print(f"{len(courses)} deshna courses, {len(schedule)} schedule rows "
          f"-> {args.out}/deshna-seed.sql")
    if not schedule:
        sys.exit("no schedule rows parsed — wrong dump?")


if __name__ == "__main__":
    main()
